# Generated by Django 4.0.4 on 2022-06-04 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_user_userfollowers_user_userfollows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userFollowers',
        ),
    ]
