# Generated by Django 4.0.4 on 2022-09-23 22:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investmentApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencySplitPref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=6)),
                ('percentage', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('userId', models.ManyToManyField(related_name='userPortfolioPref', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
