# Generated by Django 4.1.1 on 2022-09-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dcaFrequency',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='user',
            name='portfolioSplitPreference',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='currencysplitpref',
            name='currency',
            field=models.CharField(max_length=10),
        ),
    ]
