# Generated by Django 4.1.1 on 2022-09-29 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_user_dcafrequency_user_portfoliosplitpreference_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrencySplitPref',
        ),
    ]
